# SPDX-License-Identifier: GPL-2.0-only
TECHPACK?=y

techpack-dirs := $(shell find $(srctree)/techpack -maxdepth 1 -mindepth 1 -type d -not -name ".*" -not -name "camera*")
techpack-dirs := $(filter-out $(srctree)/techpack/data,$(techpack-dirs))
ifeq ($(CONFIG_MACH_XIAOMI_CITRUS),y)
techpack-dirs += $(srctree)/techpack/camera-xiaomi
else
techpack-dirs += $(srctree)/techpack/camera
endif
obj-${TECHPACK} += stub/ $(addsuffix /,$(subst $(srctree)/techpack/,,$(techpack-dirs)))
header-${TECHPACK} += $(addsuffix /include/uapi/,$(subst $(srctree)/techpack/,,$(techpack-dirs)))
